---
- name: Update apk cache.
  apk: update_cache=yes

- name: Ensure lttng-modules build dependencies are installed.
  apk: "name={{ item }} state=present"
  with_items: "{{ lttng_modules_packages }}"

