- hosts: slave-amd64
  roles:
    - common
    - cross-compilers
    - babeltrace
    - liburcu
    - lttng-ust
    - lttng-tools
    - lttng-modules
    - lttng-analyses
    - lttng-scope
    - tracecompass
