---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define babeltrace_packages.
  set_fact:
    babeltrace_packages: "{{ __babeltrace_packages | list }}"
  when: babeltrace_packages is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- include: setup-Suse.yml
  when: ansible_os_family == 'Suse'
