---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define lttng_ust_packages.
  set_fact:
    lttng_ust_packages: "{{ __lttng_ust_packages | list }}"
  when: lttng_ust_packages is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'
