---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define compilers_packages.
  set_fact:
    compilers_packages: "{{ __compilers_packages | list }}"
  when: compilers_packages is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'
